<?php

$offerte = [
    ["img" => "./img/comecostruireunalieno.png", "title" => "come costruire un alieno in offerta!", "desc" => "offerta speciale su questo titolo molto criticato e acclamato allo stesso tempo", "link" => "libro.php?info=3"],
    ["img" => "./img/themartian.png", "title" => "soppravvissuto the martian a un prezzo speciale", "desc" => "goditi questo titolo a un prezzo che non ti puoi lasciare scappare", "link" => "libro.php?info=0"],
    ["img" => "./img/cvlt.png", "title" => "cvlt di salmo e noys in offerta", "desc" => "in occasione dell uscita di questo album il prezzo è sto tagliato esattamente a metà", "link" => "disco.php?info=9"],
    ["img" => "./img/machete4.png", "title" => "machete mixtape IIII ad un prezzo assurdo!", "desc" => "in occasione del restock di questo album abbiamo deciso di metterlo a un prezzo che potrebbe farvi decidere di acquistarne un paio per voi e per i vostri amici", "link" => "disco.php?info=13"],
];

$libri = [
    ["id" => 0, "img" => "./img/themartian.png", "title" => "The Martian", "desc" => "Da questo romanzo il grande film della Twentieth Century Fox SOPRAVVISSUTO - THE MARTIAN Mark Watney è stato uno dei primi astronauti a mettere piede su Marte. Ma il momento di gloria è durato troppo poco. Un’improvvisa tempesta lo ha quasi ucciso e i suoi compagni di spedizione, credendolo morto, hanno abbandonato il pianeta rosso per fare ritorno sulla Terra. Mark si ritrova completamente solo su un pianeta inospitale e non ha nessuna possibilità di mandare un segnale alla base. E in ogni caso i viveri non basterebbero fino all’arrivo di una nuova spedizione. Nonostante tutto, con grande risolutezza Mark decide di tentare il possibile per sopravvivere. Ricorrendo alle sue conoscenze scientifiche e a una gran dose di ottimismo e tenacia, decide di affrontare un problema dopo l’altro senza perdersi d’animo. Fino a quando gli ostacoli si faranno insormontabili…", "price" => 19.99],
    ["id" => 1, "img" => "./img/le39chiavi.png", "title" => "le 39 chiavi", "desc" => "La raccolta completa della serie di avventure firmata dai più importanti scrittori americani. La caccia al tesoro più pericolosa di sempre è iniziata. Accetti la sfida? Quando Amy e Dan Cahill vengono convocati per la lettura del testamento di nonna Grace, non immaginano che da quel momento la loro vita cambierà. Dovranno infatti decidere se accettare l'eredità di un milione di dollari oppure rinunciarvi e ottenere il primo degli indizi con cui scoprire il segreto della loro famiglia. Amy e Dan non ci pensano due volte. Accettano la sfida e si trovano coinvoltI in una pericolosa caccia al tesoro intorno al mondo per svelare il segreto delle 39 chiavi e conquistare il potere che esse custodiscono. Una caccia al tesoro senza esclusione di colpi e che non permette passi falsi.", "price" => 21.99],
    ["id" => 2, "img" => "./img/lacadutadellozentir.png", "title" => "La caduta dello Zentir", "desc" => "Primo volume della saga “I rinnegati di Arest”. In una notte che sa di mistero, Nathan, John, Gwen e Sam vengono colpiti da piccoli meteoriti blu caduti dal cielo. Sono i frammenti dello Zentir, un potente e prodigioso artefatto esploso in circostanze sospette, con conseguenze devastanti per la Terra e Liiandris, il mondo magico oltre il Velo. I quattro, diventati adesso Rinnegati, scoprono non solo di possedere incredibili e inaspettati poteri, ma vengono anche in contatto con una miriade di creature magiche, malie, illusioni e pericoli provenienti da oltre il Velo. La loro vita cambia per sempre, risucchiata dal ritmo incalzante della scoperta. Dei misteriosi Cavalieri, però, danno loro la caccia mentre i Templari cercano un Varco per il mondo magico e una fazione di stregoni complotta per distruggere il delicato equilibrio che governa il tessuto magico della realtà. Coinvolti loro malgrado in una guerra di cui il mondo ignora l’esistenza, i ragazzi saranno costretti a scegliere da che parte stare. Guidati da un bibliotecario eccentrico e geniale attraverseranno mondi sconosciuti, scopriranno nuovi poteri e, soprattutto, affronteranno le loro paure più profonde.", "price" => 19.99],
    ["id" => 3, "img" => "./img/comecostruireunalieno.png", "title" => "Come costruire un alieno", "desc" => "Ci sono pochi dubbi che le leggi della fisica e della chimica siano valide sulla Terra come su altri pianeti, che un corpo cada con una certa accelerazione di gravità e che due elementi chimici possano unirsi con legami particolari anche su corpi celesti che orbitano intorno a una stella aliena. Ma non abbiamo le stesse certezze per la biologia. Anche se con declinazioni diverse, avremo sempre prede e predatori? Le loro dinamiche saranno le stesse che osserviamo sulla Terra? E la cellula, la base della vita, è proprio così indispensabile per creare corpi di dimensioni sempre maggiori? Alla ricerca di leggi universali o locali, Marco Ferrari ci conduce così su pianeti solitari in cui vive una sola specie molto semplice, e su altri ancora più ricchi della Terra, dove milioni di viventi formano un tutto simbiotico e olistico. Esploreremo corpi celesti in cui la vita si è 'fermata' a un certo punto di complessità, e altri in cui la biochimica ha portato a soluzioni del tutto differenti da quelle che potremmo trovare anche nei luoghi più remoti e oscuri del nostro pianeta. Per scoprire che, molto probabilmente, le differenze di strutture, di scheletri, di organi, di sensi e di altro sottendono sempre e solo un processo universale: l'evoluzione.", "price" => 16.99],
    ["id" => 4, "img" => "./img/herrypotter.png", "title" => "Harry Potter La serie", "desc" => "Il cofanetto della saga di Harry Potter che ha conquistato il cuore dei lettori con le illustrazioni di Kazu Kibuishi. Le coste dei romanzi all'interno del cofanetto formano il castello di Hogwarts!", "price" => 145.00],
    ["id" => 5, "img" => "./img/angeliedemoni.png", "title" => "Angeli e demoni", "desc" => "Marchiati a fuoco, prima di essere barbaramente uccisi ed esposti come monito per le strade di Roma. Questa è la sorte che toccava agli Illuminati, l'antica setta di scienziati perseguitata in secoli oscuri dalla Chiesa cattolica. Un rituale crudele che Robert Langdon ben conosce. Ma quando la storia si ripresenta nella sua bruta realtà, il fascino si trasforma in raccapriccio. Svegliato in piena notte, messo a forza su un prototipo di aereo a idrogeno liquido, trasportato in un'ora dagli Stati Uniti in Svizzera, il professor Langdon è costretto a esaminare, nei laboratori del CERN a Ginevra, un cadavere orrendamente mutilato. Sul petto della vittima - impresso a fuoco - il terribile segno degli Illuminati: lo scienziato ucciso ha difeso fino all'ultimo il segreto di un'arma sperimentale di capacità distruttive superiori a quelle del nucleare, un'arma ora scomparsa, rubata dagli assassini.", "price" => 14.25],
    ["id" => 6, "img" => "./img/divinacommedia.png", "title" => "Divina Commedia", "desc" => "A 700 anni dalla morte di Dante, il poeta che ci ha regalato la massima opera letteraria mondiale, abbiamo realizzato una meravigliosa edizione integrale in unico volume che raccoglie Inferno, Purgatorio e Paradiso, volutamente impaginato senza annotamenti, (ma con gli utilissimi riassunti delle tre cantiche a fine libro) per restituire al lettore tutta l'emozione del capolavoro originale. Un'opera monumentale che ci viene invidiata in tutto il mondo e che il sommo poeta fiorentino Dante Alighieri ha saputo elevare a punto di riferimento globale per la letteratura non soltanto italiana, a partire dal '300. Un libro importante, in un formato da biblioteca personale, ad un prezzo conveniente, che non può mancare nella tua collezione.", "price" => 16.20],
    ["id" => 7, "img" => "./img/montecristo.png", "title" => "Il conte di Montecristo", "desc" => "Da capolavoro del romanzo popolare a capolavoro del romanzo: la storia della fortuna de 'Il conte di Montecristo' si potrebbe condensare nella lenta caduta di un aggettivo. Fin dal suo primo apparire, in quella Francia degli anni Quaranta dell'Ottocento che era il più fervido e convulso laboratorio delle rivoluzioni europee, la storia dell'eroe borghese Edmond Dantès, eponimo della sfortuna e dell'ingiustizia, che si trasforma in spietato giustiziere, fu accolta dalle migliaia di avidi lettori di feuilleton come la più iperbolica incarnazione dello spirito del tempo. Un successo fulmineo, sancito dall'immediato passaggio all'edizione in volume e da un incredibile numero di ristampe e traduzioni. Ma fin da subito, quell'aggettivo, 'popolare', suonò, in tutta una parte della critica colta, come una netta discriminazione, se non come una condanna. Al contrario, il 'Montecristo' deve oggi essere situato nel posto che merita: all'apice della più felice stagione del romanzo europeo. Condotta sul testo francese meticolosamente stabilito da Claude Schopp, questa edizione comprende, oltre alla prefazione di Schopp, un apparato di note al testo, nonché un dizionario dei personaggi e delle persone storiche e un Indice dei luoghi.", "price" => 14.35],
    ["id" => 8, "img" => "./img/ioete.png", "title" => "Io e te", "desc" => "Barricato in cantina per trascorrere di nascosto da tutti la sua settimana bianca, Lorenzo, un quattordicenne introverso e un po' nevrotico, si prepara a vivere il suo sogno solipsistico di felicità: niente conflitti, niente fastidiosi compagni di scuola, niente commedie e finzioni. Il mondo con le sue regole incomprensibili fuori della porta e lui stravaccato su un divano, circondato di Coca-Cola, scatolette di tonno e romanzi horror. Sarà Olivia, che piomba all'improvviso nel bunker con la sua ruvida e cagionevole vitalità, a far varcare a Lorenzo la linea d'ombra, a fargli gettare la maschera di adolescente difficile e accettare il gioco caotico della vita là fuori. Con questo racconto di formazione Ammaniti aggiunge un nuovo, lancinante scorcio a quel paesaggio dell'adolescenza di cui è impareggiabile ritrattista. E ci dà con Olivia una figura femminile di fugace e struggente bellezza.", "price" => 11.35],
    ["id" => 9, "img" => "./img/billysummers.png", "title" => "Billy Summers", "desc" => "Billy Summers è un sicario, il migliore sulla piazza, ma ha una sua etica: accetta l'incarico solo se il bersaglio è un uomo davvero spregevole. Ora ha deciso di uscire dal giro, ma prima deve portare a termine un'ultima missione. Veterano decorato della guerra in Iraq, Billy è tra i più abili cecchini al mondo: non ha mai sbagliato un colpo, non si è mai fatto beccare - una specie di Houdini quanto si tratta di svanire nel nulla a lavoro compiuto. Cosa potrebbe andare storto? Stavolta, praticamente tutto.", "price" => 20.80],
    ["id" => 10, "img" => "./img/ventidueundicisessantatre.png", "title" => "22/11/'63", "desc" => "Jake Epping ha trentacinque anni, è professore di inglese al liceo di Lisbon Falls, nel Maine, e arrotonda lo stipendio insegnando anche alla scuola serale. Vive solo, ma ha parecchi amici sui quali contare, e il migliore è Al, che gestisce la tavola calda. È proprio lui a rivelare a Jake il segreto che cambierà il suo destino: il negozio in realtà è un passaggio spaziotemporale che conduce al 1958. Al coinvolge Jake in una missione folle - e follemente possibile: impedire l'assassinio di Kennedy. Comincia così la nuova esistenza di Jake nel mondo di Elvis, James Dean e JFK, delle automobili interminabili e del twist, dove convivono un'anima inquieta di nome Lee Harvey Oswald e la bella bibliotecaria Sadie Dunhill. Che diventa per Jake l'amore della vita. Una vita che sovverte tutte le regole del tempo conosciute. E forse anche quelle della Storia.", "price" => 39.99],
];

$dischi = [
    ["id" => 0, "img" => "./img/theisland.png", "title" => "The Island", "desc" => "album di salmo anno 2011", "price" => 10.99],
    ["id" => 1, "img" => "./img/deathusb.png", "title" => "DEATH USB", "desc" => "album di salmo anno 2012", "price" => 17.99],
    ["id" => 2, "img" => "./img/midnite.png", "title" => "Midnite", "desc" => "album di salmo anno 2013", "price" => 17.99],
    ["id" => 3, "img" => "./img/documentary.png", "title" => "S.A.L.M.O", "desc" => "album di salmo anno 2014", "price" => 13.99],
    ["id" => 4, "img" => "./img/hellvisback.png", "title" => "Hellvisback", "desc" => "album di salmo anno 2016", "price" => 15.99],
    ["id" => 5, "img" => "./img/hellvisbackplatinum.png", "title" => "Hellvisback Platinum", "desc" => "album di salmo anno 2016", "price" => 17.99],
    ["id" => 5, "img" => "./img/playlist.png", "title" => "Playlist", "desc" => "album di salmo anno 2018", "price" => 19.99],
    ["id" => 6, "img" => "./img/flop.png", "title" => "Flop", "desc" => "album di salmo è un flop 2021 (citazione per chi ha ascoltato l album, in verità è un gran album)", "price" => 11.99],
    ["id" => 7, "img" => "./img/blocco181.png", "title" => "BLOCCO 181", "desc" => "album di salmo anno 2022", "price" => 8.99],
    ["id" => 8, "img" => "./img/unplugged.png", "title" => "Salmo Unplugged", "desc" => "album di salmo anno 2023", "price" => 19.99],
    ["id" => 9, "img" => "./img/cvlt.png", "title" => "cvlt", "desc" => "album di salmo e noyz anno 2023", "price" => 18.99],
    ["id" => 10, "img" => "./img/machete1.png", "title" => "machete mixtape I", "desc" => "album della Machete Empire Records anno 2012", "price" => 9.99],
    ["id" => 11, "img" => "./img/machete2.png", "title" => "machete mixtape II", "desc" => "album della Machete Empire Records anno 2012", "price" => 17.99],
    ["id" => 12, "img" => "./img/machete3.png", "title" => "machete mixtape III", "desc" => "album della Machete Empire Records anno 2014", "price" => 7.99],
    ["id" => 13, "img" => "./img/machete4.png", "title" => "machete mixtape IIII", "desc" => "album della Machete Empire Records anno 2019", "price" => 23.99],
    ["id" => 14, "img" => "./img/xdvr.png", "title" => "Xdvr", "desc" => "album di sfera anno 2015", "price" => 9.89],
    ["id" => 15, "img" => "./img/sferaebbasta.png", "title" => "Sfera Ebbasta", "desc" => "album di sfera anno 2016", "price" => 11.69],
    ["id" => 16, "img" => "./img/rockstar.png", "title" => "ROCKSTAR", "desc" => "album di sfera anno 2018", "price" => 30.99],
    ["id" => 17, "img" => "./img/famoso.png", "title" => "famoso", "desc" => "album di sfera anno 2020", "price" => 9.99],
    ["id" => 18, "img" => "./img/italiano.png", "title" => "italiano", "desc" => "album di sfera anno 2022", "price" => 27.99],
    ["id" => 19, "img" => "./img/x2vr.png", "title" => "X2VR", "desc" => "album di sfera anno 2023", "price" => 20.17],
    ["id" => 20, "img" => "./img/album.png", "title" => "album", "desc" => "album di ghali anno 2017", "price" => 10.49],
    ["id" => 21, "img" => "./img/lvas.png", "title" => "lunga vita a sto", "desc" => "album di ghali anno 2017", "price" => 10.49],
    ["id" => 21, "img" => "./img/dna.png", "title" => "DNA", "desc" => "album di ghali anno 2020", "price" => 19.49],
    ["id" => 22, "img" => "./img/sensazioneultra.png", "title" => "sensazione ultra", "desc" => "album di ghali anno 2022", "price" => 23.80],
    ["id" => 23, "img" => "./img/pizzakebabv1.png", "title" => "PIZZA KEBAB VOL.1", "desc" => "album di ghali anno 2023", "price" => 18.81],
];